# Generated by Django 4.2.7 on 2026-04-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests_app', '0007_add_chatbot_model'),
        ('blood_requests_app', '0008_add_request_to_chatmessage'),
    ]

    operations = [
    ]
