# Generated by Django 4.2.7 on 2026-04-17
# Safe migration that handles missing indexes gracefully

from django.db import migrations
from django.db import connection


def safe_rename_index(apps, schema_editor, old_name, new_name, table_name):
    """Safely rename an index, skipping if old index doesn't exist"""
    with connection.cursor() as cursor:
        # Check if old index exists
        cursor.execute("""
            SELECT indexname 
            FROM pg_indexes 
            WHERE tablename = %s AND indexname = %s
        """, [table_name, old_name])
        
        if cursor.fetchone():
            # Index exists, rename it
            try:
                cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
                print(f"  ✅ Renamed index: {old_name} -> {new_name}")
            except Exception as e:
                print(f"  ⚠️  Could not rename {old_name}: {e}")
        else:
            print(f"  ⏭️  Skipped: Index {old_name} does not exist")


def rename_blood_request_indexes(apps, schema_editor):
    """Safely rename BloodRequest indexes"""
    table_name = 'blood_requests_app_bloodrequest'
    
    safe_rename_index(
        apps, schema_editor,
        'blood_reque_status_852f41_idx',
        'blood_reque_status_1ebe82_idx',
        table_name
    )
    
    safe_rename_index(
        apps, schema_editor,
        'blood_reque_city_1b4467_idx',
        'blood_reque_city_d94778_idx',
        table_name
    )
    
    safe_rename_index(
        apps, schema_editor,
        'blood_reque_latitud_12345_idx',
        'blood_reque_latitud_5a2dc9_idx',
        table_name
    )


def rename_chatbot_indexes(apps, schema_editor):
    """Safely rename ChatbotConversation indexes"""
    table_name = 'blood_requests_app_chatbotconversation'
    
    safe_rename_index(
        apps, schema_editor,
        'blood_reque_session__idx',
        'blood_reque_session_c540d3_idx',
        table_name
    )
    
    safe_rename_index(
        apps, schema_editor,
        'blood_reque_user__idx',
        'blood_reque_user_id_d3eebb_idx',
        table_name
    )


def rename_donor_location_indexes(apps, schema_editor):
    """Safely rename DonorLocationHistory indexes"""
    table_name = 'blood_requests_app_donorlocationhistory'
    
    safe_rename_index(
        apps, schema_editor,
        'blood_reque_donor_i_ghi789_idx',
        'blood_reque_donor_i_2e9538_idx',
        table_name
    )


def rename_request_response_indexes(apps, schema_editor):
    """Safely rename RequestResponse indexes"""
    table_name = 'blood_requests_app_requestresponse'
    
    safe_rename_index(
        apps, schema_editor,
        'blood_reque_status_abc123_idx',
        'blood_reque_status_fe6476_idx',
        table_name
    )
    
    safe_rename_index(
        apps, schema_editor,
        'blood_reque_is_sele_def456_idx',
        'blood_reque_is_sele_a2dc65_idx',
        table_name
    )


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests_app', '0009_merge_20260416_0321'),
    ]

    operations = [
        # Create DonorRating model (this is safe)
        migrations.CreateModel(
            name='DonorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        
        # Safely rename indexes using custom Python code
        migrations.RunPython(rename_blood_request_indexes, migrations.RunPython.noop),
        migrations.RunPython(rename_chatbot_indexes, migrations.RunPython.noop),
        migrations.RunPython(rename_donor_location_indexes, migrations.RunPython.noop),
        migrations.RunPython(rename_request_response_indexes, migrations.RunPython.noop),
        
        # Update NotificationMessage field (safe)
        migrations.AlterField(
            model_name='notificationmessage',
            name='user',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='chat_notifications',
                to='accounts.user'
            ),
        ),
        
        # Add new indexes (safe - will skip if they already exist)
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'receiver', 'created_at'], name='blood_reque_sender__8cc602_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['receiver', 'is_read', 'created_at'], name='blood_reque_receive_ce8e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationmessage',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='blood_reque_user_id_828953_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationmessage',
            index=models.Index(fields=['user', 'priority', 'created_at'], name='blood_reque_user_id_20f4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='roommessage',
            index=models.Index(fields=['room', 'created_at'], name='blood_reque_room_id_deb9e5_idx'),
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['room', 'user', 'last_updated'], name='blood_reque_room_id_73b3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['receiver', 'user', 'last_updated'], name='blood_reque_receive_777d96_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user', 'created_at'], name='blood_reque_user_id_ca32c6_idx'),
        ),
        
        # Add DonorRating fields
        migrations.AddField(
            model_name='donorrating',
            name='rated_user',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='received_ratings',
                to='accounts.user'
            ),
        ),
        migrations.AddField(
            model_name='donorrating',
            name='rater',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='given_ratings',
                to='accounts.user'
            ),
        ),
        migrations.AddField(
            model_name='donorrating',
            name='request',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='ratings',
                to='blood_requests_app.bloodrequest'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='donorrating',
            unique_together={('rater', 'rated_user', 'request')},
        ),
    ]
