# Generated by Django 4.2.7 on 2026-04-16 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood_requests_app', '0009_merge_20260416_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='bloodrequest',
            new_name='blood_reque_status_1ebe82_idx',
            old_name='blood_reque_status_852f41_idx',
        ),
        migrations.RenameIndex(
            model_name='bloodrequest',
            new_name='blood_reque_city_d94778_idx',
            old_name='blood_reque_city_1b4467_idx',
        ),
        migrations.RenameIndex(
            model_name='bloodrequest',
            new_name='blood_reque_latitud_5a2dc9_idx',
            old_name='blood_reque_latitud_12345_idx',
        ),
        migrations.RenameIndex(
            model_name='chatbotconversation',
            new_name='blood_reque_session_c540d3_idx',
            old_name='blood_reque_session__idx',
        ),
        migrations.RenameIndex(
            model_name='chatbotconversation',
            new_name='blood_reque_user_id_d3eebb_idx',
            old_name='blood_reque_user__idx',
        ),
        migrations.RenameIndex(
            model_name='donorlocationhistory',
            new_name='blood_reque_donor_i_2e9538_idx',
            old_name='blood_reque_donor_i_ghi789_idx',
        ),
        migrations.RenameIndex(
            model_name='requestresponse',
            new_name='blood_reque_status_fe6476_idx',
            old_name='blood_reque_status_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='requestresponse',
            new_name='blood_reque_is_sele_a2dc65_idx',
            old_name='blood_reque_is_sele_def456_idx',
        ),
        migrations.AlterField(
            model_name='notificationmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'receiver', 'created_at'], name='blood_reque_sender__8cc602_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['receiver', 'is_read', 'created_at'], name='blood_reque_receive_ce8e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationmessage',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='blood_reque_user_id_828953_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationmessage',
            index=models.Index(fields=['user', 'priority', 'created_at'], name='blood_reque_user_id_20f4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='roommessage',
            index=models.Index(fields=['room', 'created_at'], name='blood_reque_room_id_deb9e5_idx'),
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['room', 'user', 'last_updated'], name='blood_reque_room_id_73b3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['receiver', 'user', 'last_updated'], name='blood_reque_receive_777d96_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user', 'created_at'], name='blood_reque_user_id_ca32c6_idx'),
        ),
        migrations.AddField(
            model_name='donorrating',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donorrating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donorrating',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blood_requests_app.bloodrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='donorrating',
            unique_together={('rater', 'rated_user', 'request')},
        ),
    ]
