# Generated by Django 4.2.7 on 2026-04-16 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donors', '0003_add_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorrating',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donorrating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
