# Generated by Django 4.2.7 on 2026-04-16 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _run_postgres_sql(schema_editor, sql):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(sql)


def drop_legacy_user_index(apps, schema_editor):
    _run_postgres_sql(
        schema_editor,
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_indexes
                WHERE indexname = 'accounts_us_user_id_abc123_idx'
            ) THEN
                DROP INDEX accounts_us_user_id_abc123_idx;
            END IF;
        END $$;
        """,
    )


def rename_privacy_index_forward(apps, schema_editor):
    _run_postgres_sql(
        schema_editor,
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_indexes
                WHERE indexname = 'accounts_pa_user_id_8d9f3a_idx'
            ) THEN
                ALTER INDEX accounts_pa_user_id_8d9f3a_idx RENAME TO accounts_pa_user_id_92b775_idx;
            END IF;
        END $$;
        """,
    )


def rename_privacy_index_reverse(apps, schema_editor):
    _run_postgres_sql(
        schema_editor,
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_indexes
                WHERE indexname = 'accounts_pa_user_id_92b775_idx'
            ) THEN
                ALTER INDEX accounts_pa_user_id_92b775_idx RENAME TO accounts_pa_user_id_8d9f3a_idx;
            END IF;
        END $$;
        """,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_favoritedonor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='donorprofile',
            options={'verbose_name': 'Donor Profile', 'verbose_name_plural': 'Donor Profiles'},
        ),
        migrations.AlterModelOptions(
            name='notificationsettings',
            options={'verbose_name': 'Notification Settings', 'verbose_name_plural': 'Notification Settings'},
        ),
        migrations.AlterModelOptions(
            name='privacysettings',
            options={'verbose_name': 'Privacy Settings', 'verbose_name_plural': 'Privacy Settings'},
        ),
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.RunPython(drop_legacy_user_index, migrations.RunPython.noop),
        migrations.RenameField(
            model_name='donorprofile',
            old_name='preferred_locations',
            new_name='badges',
        ),
        migrations.RenameField(
            model_name='donorprofile',
            old_name='auto_accept_emergency',
            new_name='has_recent_illness',
        ),
        migrations.RenameField(
            model_name='donorprofile',
            old_name='allergies',
            new_name='medical_restrictions',
        ),
        migrations.RenameField(
            model_name='donorprofile',
            old_name='medical_conditions',
            new_name='recent_illness_details',
        ),
        migrations.RenameField(
            model_name='privacysettings',
            old_name='allow_messages',
            new_name='enable_chat_requests',
        ),
        migrations.RenameField(
            model_name='privacysettings',
            old_name='data_sharing_consent',
            new_name='show_last_donation_date',
        ),
        migrations.RenameField(
            model_name='privacysettings',
            old_name='show_phone',
            new_name='show_phone_number',
        ),
        migrations.RunPython(rename_privacy_index_forward, rename_privacy_index_reverse),
        migrations.RemoveField(
            model_name='donorprofile',
            name='availability_schedule',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='last_donation_date',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='max_distance_km',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='details',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='auto_disable_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available to Donate ✅'), ('not_available', 'Not Available ❌'), ('busy', 'Busy ⏳'), ('temporarily_deferred', 'Temporarily Deferred 🚫')], default='available', max_length=25),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='donation_frequency_preference',
            field=models.CharField(choices=[('regular', 'Regular (Every 3 months)'), ('occasional', 'Occasional'), ('emergency_only', 'Emergency Only')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_donation_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='preferred_donation_centers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='live_location_during_emergency',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='location_sharing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='device_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='location_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='system_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Changed'), ('settings_update', 'Settings Updated'), ('profile_update', 'Profile Updated')], max_length=20),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
