# Generated by Django 4.2.7 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_follow_alter_donorprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_notification_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completion_seen',
            field=models.BooleanField(default=False),
        ),
    ]
