# Generated by Django - Fix for missing columns in notifications table
# This migration adds all fields missing from 0001_initial

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        # Add category field (MISSING from initial migration)
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(
                choices=[('medical', 'Medical'), ('system', 'System'), ('social', 'Social'), ('general', 'General')],
                default='general',
                max_length=20
            ),
        ),
        
        # Add delivered_at field (MISSING from initial migration)
        migrations.AddField(
            model_name='notification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        
        # Update priority choices to match model
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(
                choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')],
                default='medium',
                max_length=10
            ),
        ),
        
        # Update notification_type choices to match model
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[('donation_reminder', 'Donation Reminder'), ('blood_request', 'Blood Request Alert'), ('status_update', 'Status Update Required'), ('eligibility', 'Eligibility Notice'), ('general', 'General Announcement')],
                max_length=50
            ),
        ),
    ]
