# Generated by Django 4.2.7 on 2026-04-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_fix_push_sent_default'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_b9c0e7_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical'), ('system', 'System'), ('social', 'Social'), ('reminder', 'Reminder')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='push_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx'),
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
    ]
